# Generated by Django 4.1.1 on 2022-09-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendrequest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Freind_Request',
            new_name='Friend_Request',
        ),
    ]
